#! /bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:

function AddPtr() {
	echo "##### git add ${1?Must specify submodule}"
	#git add ${1?Must specify submodule}
	echo "##### git commit -m 'update pointer'"
	#git commit -m 'update pointer'
	echo "##### git push"
	#git push
}

top=$(pwd)
for x in $(git submodule status --recursive | awk '/^+/ {print $2}')
do
	echo "##### processing $x"
	echo "##### change to $x"
	cd $x
	echo "##### back one directory"
	cd ..
	echo "##### current PWD ${PWD}"
	AddPtr $x
	cd ..
	while [ ${PWD} != $top ]
	do
		AddPtr ${PWD}
	done
done
