#! /bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:

# install necessary tools
sudo apt-get install -y autoconf automake libtool

# loop thru submodules
for x in suba subb subc
do
	cd $x
	autoreconf --verbose --install --force
	./configure
	make
done

autoreconf --verbose --install --force
./configure
make
